#pragma once
//Qt libraries
#include <QtWidgets>
#include <QtXml>
#include <QtXmlPatterns>
//Smart pointers
#include <memory>
//STL libraries
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <functional>
//Net-Snmp library
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/version.h>
